Add detection of EU users for Consent Modal
dospore/gmx-interface pull request #124
Opened 2022-09-01 04:51 UTC by rogue-hacker

For inside EU: 

![image](https://user-images.githubusercontent.com/19278287/187833871-9b82dc16-7ea4-46c6-8f6c-6145515700b4.png)

For outside EU:

![image](https://user-images.githubusercontent.com/19278287/187833902-ada24914-e771-41e6-9bc1-7f2585758168.png)

2022-09-02 19:50 UTC, doylio approved these changes

2022-09-02 19:53 UTC, doylio reviewed
It seems like this dialogue box will never appear to non-EU members, because they will automatically have "consentAcknowledged" set to true on boot

2022-09-05 02:18 UTC, dospore commented on src/components/ConsentModal/ConsentModal.js
> +    }
I feel we cant default consent to true

2022-09-05 02:20 UTC, dospore commented on src/components/ConsentModal/ConsentModal.js
> +  );
Is this the same text?

2022-09-05 02:57 UTC, dospore requested changes
Requesting changes on the default opt in unless we add a way to opt out

2022-10-07 03:24 UTC, closed without merging